name: Generate Neon Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Generate neon contribution snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}

          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#38BDF8&color_dots=#020617,#1E1B4B,#312E81,#6D28D9,#0EA5E9
            dist/github-contribution-grid-snake-dark.svg?color_snake=#8B5CF6&color_dots=#020617,#172554,#312E81,#6D28D9,#38BDF8

      - name: Publish snake to output branch
        uses: crazy-max/ghaction-github-pages@v5
        with:
          build_dir: dist
          target_branch: output

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
